### ISSUE TITLE
Question re. beta coefficients for health predictors

### ISSUE THREAD

**Issue by colinraybrian** [Ottawa-mHealth/predictive-algorithms#12]
This question pertains to decisions made for PMML- MPoRT Female v2.0.0.txt. 
How did you decide the numerical value of the beta coefficients for each individual predictor (e.g.PhysicalActivity_cont is assigned  beta="-0.928355359618802")? Was it based on the single study or an aggregation of data?

@DougManuel

**Comment by DougManuel** [comment]
The beta coefficients are directly from the [MPoRT algorithm](http://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1002082). So, the beta coefficients are from a single study. 

The study used a linked population health survey with about 1 million person-years follow-up. Similar studies are available in about 100 countries, albeit most those do not have their surveys linked to mortality.
